// 设备
export const SET_DEVICES_LIST = 'SET_DEVICES_LIST'
export const SET_DEVICE_ITEM = 'SET_DEVICE_ITEM'
export const SET_FORMDATA_CONNECT = 'SET_FORMDATA_CONNECT'
export const SET_FORMDATA_DETAIL = 'SET_FORMDATA_DETAIL'
export const SET_FORMDATA_REMARK = 'SET_FORMDATA_REMARK'
export const SET_FORMDATA_FILES = 'SET_FORMDATA_FILES'

// 工单
export const SET_WORKORDERS_LIST = 'SET_WORKORDERS_LIST'
export const SET_WORKORDER_ITEM = 'SET_WORKORDER_ITEM'
export const SET_ITEMSTATE = 'SET_ITEMSTATE'

// 用户
export const SET_USER_PROFILE = 'SET_USER_PROFILE'